apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.appLabel }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appLabel }}
    spec:
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: "{{ .Values.deployment.container.image.repository }}:{{ .Values.deployment.container.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.container.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.deployment.container.resources.requests.cpu | quote }}
            memory: {{ .Values.deployment.container.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.deployment.container.resources.limits.cpu | quote }}
            memory: {{ .Values.deployment.container.resources.limits.memory | quote }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.deployment.container.probe.port }}
          initialDelaySeconds: {{ .Values.deployment.container.probe.livenessInitialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.container.probe.livenessPeriodSeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.deployment.container.probe.port }}
          initialDelaySeconds: {{ .Values.deployment.container.probe.readinessInitialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.container.probe.readinessPeriodSeconds }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        ports:
        - containerPort: {{ .Values.deployment.container.port.containerPort }}
          name: {{ .Values.deployment.container.port.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.deployment.appLabel }}
spec:
  selector:
    app: {{ .Values.deployment.appLabel }}
  ports:
  - protocol: {{ .Values.service.port.protocol }}
    port: {{ .Values.service.port.port }}
    targetPort: {{ .Values.service.port.targetPort }}
    name: {{ .Values.service.port.name }}
  type: {{ .Values.service.type }}
