apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSet.name }}
  labels:
    app: {{ .Values.statefulSet.appLabel }}
spec:
  serviceName: {{ .Values.statefulSet.serviceName }}
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulSet.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulSet.appLabel }}
    spec:
      containers:
      - name: {{ .Values.statefulSet.container.name }}
        image: "{{ .Values.statefulSet.container.image.repository }}:{{ .Values.statefulSet.container.image.tag }}"
        imagePullPolicy: {{ .Values.statefulSet.container.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        ports:
{{- range .Values.statefulSet.container.ports }}
        - containerPort: {{ .containerPort }}
          name: {{ .name }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.statefulSet.appLabel }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Values.statefulSet.appLabel }}
  ports:
{{- range .Values.service.ports }}
  - protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    name: {{ .name }}
{{- end }}
